---

scenario:
  name: default

driver:
  name: podman

dependency:
  name: galaxy

platforms:
  - name: instance
    image: geerlingguy/docker-ubi8-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: testinfra
  options:
    vvv: True
  additional_files_or_dirs:
    - ../resources/tests/
